function [figurehandle,newfigurecounter]=compiled_hydraplot(BatchDataStructure,oldfigurecounter)

%==========================================================================
%% CODE DESCRIPTION
%==========================================================================
%  This function constructs a binary hydra-effect plot using data copiled  
%  from a batch run using a hydra-effect threshold of 0.  
%
%  [figurehandle,newfigurecounter]=compiledhydraplot(B,oldfigurecounter)
%
%   INPUTS:
%   -------
%   BatchDataStructure  : 
%       Data structure constructed via batchinputs_create.m
%   oldfigurecounter    : scalar
%
%
%   OUTPUTS:
%   --------
%   figurehandle        : Handle for the figure generated by this script
%   figurecounter       : Figure counter value corresponding to the figure
%                           generated by this script
%
%   DEPENDENCIES: 
%   -------------
%   - reproductioninputs_extract [script]
%
%   USED BY: 
%   ---------
%   figuregenerator_userchoice.m
%   *_figuregenerator_manuscript.m
%   
%
%   QUESTIONS about the code set? 
%               Email Laura Strube at LFStrube@gmail.com
%
%% ------------------------------------------------------------------------
%==========================================================================
%% START CODE
%==========================================================================

%% (I) SET LATEX AS THE DEFAULT INTERPRETER
    %"groot"= root of all graphics objects
    set(groot,'defaultAxesTickLabelInterpreter','latex');  
    set(groot,'defaultTextInterpreter','latex');
    set(groot,'defaultLegendInterpreter','latex');
    set(groot,'defaultColorBarTickLabelInterpreter','latex');

%% (II) EXTRACT RUN CONDITIONS
    ReproductionInputs=BatchDataStructure(1).D.ReproductionInputs;
    reproductioninputs_extract

%% (III) FORMAT AXIS LABELS

    %Default axis label formatting
    bp1label=sprintf('%s',bp1);
    bp2label=sprintf('%s',bp2);

    %Overwrite default and convert to a symbol if the parameter is a greek letter
    if bifpar1 == 5 || bifpar1 == 6
        bp1label= sprintf('$\\%s$',bp1);
        bp2label=sprintf('$%s$',bp2);
    end
    
    if bifpar2 == 5 || bifpar2 == 6
        bp1label=sprintf('$%s$',bp1);
        bp2label= sprintf('$\\%s$',bp2);
    end

 %% (IV) PROCESS DATA FOR COMPILED HYDRA-EFFECT PLOT
    
    %Initialize Array
    HHydra=zeros(size(BatchDataStructure(1).D.Average_TDataArray));

    %Process data for individual hydra-effect plots (not visualized)
    for i=1:1:length(BatchDataStructure)
    binaryhydrathreshold=0;  
    [~,~,BinaryHydra{i}]=...
            calculatehydra(BatchDataStructure(i).D.Average_TDataArray,BatchDataStructure(i).D.Average_DFDataArray,binaryhydrathreshold);
    end

    % Process data for compiled hydra-effect plot (visualized with this script)
    for i=1:1:length(BatchDataStructure)
        IndividualHydra=BinaryHydra{i};
        [hydra_m,hydra_n]=size(IndividualHydra);
        for j=1:1:hydra_m
            for k=1:1:hydra_n
                if IndividualHydra(j,k)==1
                    HHydra(j,k)=1;
                end
            end
        end
    end

 %% (V) GENERATE COMPILED HYDRA-EFFECT PLOT FIGURE

    colorbarlabel='Hydra Effect';
    figuretitle={BatchDataStructure(i).LatexBatchDate, 'Net Hydra Effect Across the Range of Sampled Parameters'};
    figurecounter=0;
    [figurehandle,newfigurecounter]=hydraeffectplot('BinaryHydra',HHydra,bifpar1,bifpar2,'none',...
        increm1,increm2,bp1label,bp2label,colorbarlabel,figuretitle,...
        oldfigurecounter);

%% (VI) RESET TEXT INTERPRETER TO DEFAULT
    set(groot,'defaultAxesTickLabelInterpreter','none');  
    set(groot,'defaultTextInterpreter','none');
    set(groot,'defaultLegendInterpreter','none');
    set(groot,'defaultColorBarTickLabelInterpreter','none');  

end
%==========================================================================
%% END CODE
%==========================================================================