function [figurehandle,newfigurecounter]=lhsvisualization(BatchDataStructure,figuretitle,oldfigurecounter)
%==========================================================================
%% CODE DESCRIPTION
%==========================================================================
%  This function constructs a figure visualizing a 2D array of LHS sampled
%  points from the xrange and yrange and used in the construction of data 
%  in BatchDataStructure.
%
% function [figurehandle,newfigurecounter]=...
% lhsvisualization(BatchDataStructure,xrange,yrange,oldfigurecounter)
%
%   INPUTS:
%   -------
%   BatchDataStructure  : 
%       Data structure constructed via batchinputs_create.m
%   xrange=[xmin xmax]  : 
%       Range of first parameter sampled via LHS [scalar,scalar]
%   yrange=[ymin ymax]  : 
%       Range of second parameter sampled via LHS [scalar,scalar]
%   figuretitle         : Cell array of strings
%   oldfigurecounter    : scalar
%
%
%   OUTPUTS:
%   --------
%   figurehandle        : Handle for the figure generated by this script
%   figurecounter       : Figure counter value corresponding to the figure
%                           generated by this script
%
%   DEPENDENCIES: 
%   -------------
%   None
%
%   USED BY: 
%   ---------
%   figuregenerator_userchoice.m
%   *_figuregenerator_manuscript.m
%   
%
%
%   QUESTIONS about the code set? 
%               Email Laura Strube at LFStrube@gmail.com
%
%% ------------------------------------------------------------------------
%==========================================================================
%% START CODE
%==========================================================================

%% (I) SET LATEX AS THE DEFAULT INTERPRETER
    %"groot"= root of all graphics objects
    set(groot,'defaultAxesTickLabelInterpreter','latex');  
    set(groot,'defaultTextInterpreter','latex');
    set(groot,'defaultLegendInterpreter','latex');
    set(groot,'defaultColorBarTickLabelInterpreter','latex');

%% (II) INITIALIZE FIGURE
    figurehandle=figure;
    newfigurecounter=oldfigurecounter+1;

%% (III) EXTRACT LHS PARAMETER NAMES AND RANGES
    paramnames=fieldnames(BatchDataStructure(1).LHSSpecs);
    pn1=paramnames{1};
    pn2=paramnames{2};
    xrange=BatchDataStructure(1).LHSRange.(pn1);
    yrange=BatchDataStructure(1).LHSRange.(pn2);
 
%% (IV) EXTRACT THE QUANTITY OF LHS PARAMETER SETS 
    pointcount=length(BatchDataStructure); 

%% (V) EXTRACT LHS SAMPLED VALUES 
    for i=1:1:pointcount
        x(i)=BatchDataStructure(i).LHSSpecs.(pn1);
        y(i)=BatchDataStructure(i).LHSSpecs.(pn2);
    end

%% (VI) PLOT LHS SAMPLED VALUES
    % Set plot grid spacing (1 point in each grid interval)
    xtickspacing=(xrange(2)-xrange(1))/pointcount;  
    ytickspacing=(yrange(2)-yrange(1))/pointcount;

    % Plot LHS Sampled Values
    plot(x,y,'k.')
    grid on

%% (VII) FORMAT FIGURE

    % Format x-axis ticks and labels
    xticks(0:xtickspacing:xrange(2)+1);
    xtickstrings=string(xticks);
    xlab=strings(1,length(xtickstrings));
    xlab(1:((length(xtickstrings)-1)/10):length(xtickstrings))=xtickstrings(1:((length(xtickstrings)-1)/10):length(xtickstrings));
    xticklabels(xlab);

    % Format y-axis ticks and labels
    yticks(0:ytickspacing:yrange(2)+1);
    ytickstrings=string(yticks);
    ylab=strings(1,length(ytickstrings));
    ylab(1:((length(ytickstrings)-1)/10):length(ytickstrings))=ytickstrings(1:((length(ytickstrings)-1)/10):length(ytickstrings));
    yticklabels(ylab);

    % Title and Axis Labels
    title(figuretitle)
    xlabel(pn1)
    ylabel(pn2)


%% (VIII) RESET TEXT INTERPRETER TO DEFAULT
    set(groot,'defaultAxesTickLabelInterpreter','none');  
    set(groot,'defaultTextInterpreter','none');
    set(groot,'defaultLegendInterpreter','none');
    set(groot,'defaultColorBarTickLabelInterpreter','none');  
end
%==========================================================================
%% END CODE
%==========================================================================